---
title: "Variable(Visual) Star Varifications"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
#    vertical_layout: fill
    vertical_layout: scroll
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(insol)
library(rsconnect)
library(DT)
library(plotly)
```
# Home

## Column {.sidebar}


```{r}
fileInput("file1", "Choose CSV File",
        accept = c(
          "text/csv",
          "text/comma-separated-values,text/plain",
          ".csv"))
mydata <- reactive({
    req(input$file1)
    inFile <- input$file1
    if(is.null(inFile)){return(NULL)}
    read_csv(inFile$datapath) %>% 
    mutate(Ymd =insol::JD(JD,inverse = TRUE)) %>%
       mutate(Ymd = as.Date(Ymd))  %>%
      mutate(Magnitude = as.numeric( gsub("<","", Magnitude) ) + 0.99) %>%
      select(Ymd,Star_Name,Band,Magnitude,Validation_Flag) %>%
      filter(Band=="Vis.")
      
})   

```


## Column {data-width=750}

```{r}
starDust <- reactive({ 
  mydata() %>%
    group_by(Ymd,Validation_Flag) %>%
        summarize(Mean = round(mean(Magnitude),digits=1),
               Brighter = round(Mean -1,digits = 1),
               Fainter = round(Mean +1,digits= 1),
               Obs = n()) %>% 
    ungroup() %>% 
    mutate(Verify = case_when(
      (Brighter <  Mean -1) | (Fainter > Mean + 1) ~ "Yes",TRUE ~ "No")) })
  ```
  
  
```{r}
#     renderDT({starDust() %>% arrange(desc(Verify)) %>% 
#         datatable(filter = 'top',
#          extensions = 'Buttons', options = list(
#     dom = 'Bfrtip',
#     buttons = c('csv', 'excel', 'pdf')))
#   
#                   
# })
```

### Scater Plot with Validation Flag

```{r}
renderPlotly({mydata() %>% plot_ly(x=~Ymd,y=~Magnitude) %>%
    add_trace(type="scatter",mode="markers",color=~Validation_Flag,
              colors = "Set1")   %>%
            layout(yaxis = list(autorange = "reversed"))
            
    
})
```



### Daily Box Plots

```{r}
renderPlotly({
  mydata() %>% plot_ly() %>% add_boxplot(x=~Ymd,y=~Magnitude) %>% layout(yaxis = list(autorange = "reversed"))
    
    
})
```
```{r}
  renderDT({starDust() %>% arrange(desc(Verify)) %>% 
        datatable(filter = 'top',editable = TRUE)})
  
  
  
  ```
